version: 0.1
phases:
  install:
    commands:
      - npm install
      - find ./node_modules -mtime +10950 -exec touch {} \;
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket bucketarun696 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml