AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: nodejs10.x
      CodeUri: ./
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::112943594119:role/firstservice-dev-us-east-1-lambdaRole'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: ap-southeast-2